apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  labels:
    service: $APP_NAME
spec:
  ports:
    - port: 8080 # change this to the desired port if needed
  selector:
    app: $APP_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME # change this to the desired name if needed
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $APP_NAME # change this to the desired label if needed
  template:
    metadata:
      labels:
        app: $APP_NAME # change this to the desired label if needed
        routectl-name: $APP_NAME
        routectl-ns: placeholder
    spec:
      containers:
        - image: $IMAGE_NAME # change this to the desired image if needed
          name: $APP_NAME # change this to the desired name if needed
          ports:
            - containerPort: 8080 # change this to the desired port if needed
              name: http # change this to the desired name if needed
